### ISSUE TITLE
Валутна информация от множество източници

### ISSUE THREAD

**Issue by Hristov-Metodi** [vexelon-dot-net/currencybg.app#3]
Събиране на курс купува/продава от множество източници (TAVEX, Bulbank, First Investment Bank и т.н).

**ОПЦИЯ 1:** Ако има значителни разлики приложението може да предложи: Най-доброто място за деня.
**ОПЦИЯ 2:** Смятане на сума над която е рентабилно да се отиде на конкретно място (при разлика от 0,001лв за да се спечели 1лв повече трябва да се обменят 1000лв)

**Comment by petarov** [comment]
**TODO**: От кои източници можем да ползваме данни в приложението / права?

**Comment by petarov** [comment]
Започваме със следните:

1. Полана
2. Тавекс
3. ФИБ

**Comment by petarov** [comment]
Текущи **TODOs**

- [ ] Нов изглед с колони на валутите според източник
- [ ] Работещо обновяване от сървъра (запис на последно обновената дата)
- [ ] Избор на показване на Купува/Продава
- [ ] Работещо сортиране
- [ ] Работещо Simple/Advanced показване на стойности след дес. запетая
- [ ] Премахване на _ненужни_ валути, e.g., SBP
- [ ] Оправяне на service-a (?)

**Comment by petarov** [comment]
Вътре с PR #29
